<?php

/*********************************************************************
 * Extension configuration file for ext "media".
 *
 * Generated by ext 31-10-2014 21:12 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => 'ItandTel Media extended',
	'description' => 'Extends Medias for the needs of ItandTel',
	'category' => 'misc',
	'author' => 'Fabien Udriot',
	'author_email' => 'fabien.udriot@typo3.org',
	'module' => '',
	'state' => 'stable',
	'uploadfolder' => '0',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' =>
		array (
			'depends' =>
				array (
					'typo3' => '6.2.0-6.2.99',
					'media' => '',
				),
			'conflicts' =>
				array (
				),
			'suggests' =>
				array (
				),
		),
);
